spring:
  datasource:
    url: jdbc:mysql://localhost:3306/shop?characterEncoding=utf8
    username: root
    password: rlaqjawls1!
    driverClassName: com.mysql.cj.jdbc.Driver
    hikari:
      maximum-pool-size: 10
  jpa:
    database: mysql
    show-sql: true
    open-in-view: false

logging:
  level:
    root: INFO
    com:
      myshop: DEBUG
    org:
      springframework:
        security: DEBUG
